name: Acquire Activation File

# This workflow is only run manually (via the GitHub Actions tab)
on:
  workflow_dispatch: {}

env:
  UNITY_VERSION: 6000.2.7f2

jobs:
  activation:
    name: Request Manual Activation File ðŸ”‘
    runs-on: ubuntu-latest
    steps:
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: ${{ env.UNITY_VERSION }}

      - name: Upload activation file (Unity_v****.alf)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.getManualLicenseFile.outputs.filePath }}
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
